@vincent @additional_payment_by_recipient_update
Feature: Test for Payroll Additional Payment Standard
  Test-condition:
  Enable Employee Payroll Security - Yes
  Enable Inclusive Sales Tax - Yes
  Overwrite Sales Tax Code - Yes
  Enable Approval For Additional Payment - No

  Scenario: Clear data for AddPayment Voucher, Payroll Generation, Payroll Payslip
    Given user access DB "jdbc:db2://172.18.0.10:50000/GENMAIN6" with id "db2admin" and password "Taskhub1"
    Given Data is clear as in "AddPayment_ClearSQL.xls"

  Scenario Outline: Create for Payroll Additional Payment Standard
    Given user logins to Task Hub as "<Login User KEY>"
      | KEY | User Name | Password | Company |
      | 001 | vincent1  | taskhub  | (TRG6)  |
    Given user changes database connection as "<DATABASE KEY>"
      | KEY | JDBC_DRIVER               | IP_SERVER   | SERVER_PORT | DB_NAME  | USER_NAME | PASS_WORD |
      | 001 | com.ibm.db2.jcc.DB2Driver | 172.18.0.10 | 50000       | GENMAIN6 | db2admin  | Taskhub1  |
    When user navigates to "Maintenance Setup>Module Config>Module Config" screen
    Then user changes Module Config as "<Module Config KEY>"
      | KEY | Module Section                                 | Module Name                                                                                                                   | Config Type 1 | Config Value 1 | Config Type 2 | Config Value 2 |
      | 001 | Payroll>Payroll                                | Enable Inclusive Sales Tax                                                                                                    | Radio         | Yes            |               |                |
      | 001 | Payroll>Payroll                                | Enable allocate Additional Payment to different Line Item                                                                     | Radio         | No             |               |                |
      | 001 | Payroll>Payroll                                | Overwrite Sales Tax Code                                                                                                      | Radio         | Yes            |               |                |
      | 001 | Payroll>Payroll                                | Enable Approval for Additional Payment (By Recipient).                                                                        | Radio         | No             |               |                |
      | 001 | Project Costing>Project Quotation & Estimation | Disable GL Entries For Recognition                                                                                            | Radio         | Yes            |               |                |
      | 001 | Project Costing>Project Costing                | Enable to Post Project Cost to Expense GLAN/Revenue GLAN of Cost Item instead of Project WIP GLAN (exclude Payroll Timesheet) | Radio         | Yes            |               |                |
      | 002 | Payroll>Payroll                                | Enable allocate Additional Payment to different Line Item                                                                     | Radio         | Yes            |               |                |
    When user navigates to "Processing>Payroll>Additional Payment" screen
    Then page header shouble be "Additional Payment"
    When user creates new voucher in Draft state of Additional Payment by Recipient
    Then all information in Draft state of Additional Payment by Recipient should be pulled out as "<Additional Payment KEY>"
      | KEY | Voucher No | Voucher Type | Voucher Date | Description |
      | 001 | @NotBlank@ | By Recipient |              | @Blank@     |
    Then user inputs data for new voucher in Draft state of Additional Payment by Recipient as "<Recipient KEY>"
      | KEY | Description               | Voucher Date | Recipients Code | Recipients Name | Payroll Date  |
      | 001 | Test for Add payment by R |              | EMP1            |                 | @CurrentDate@ |
    Then user add data for Wage Services in Draft state of Additional Payment by Recipient as "<Wage Services KEY>"
      | KEY | No | Wage Service | Wage Service Description | Voucher Date | Ccy | Exchange Rate | Qty | Unit Price | Inclusive Tax | Sales Tax Code Default | Sales Tax Edit | Nature Amt Before Tax | Nature Amt After Tax | Commission Start Date | Commission End Date | Monthly Commission | Alloc Voucher No | Phase Sequence No | LI No |
      | 001 | 1  | ISALARY      |                          |              | SGD | 1.0           | 1   | 10         | Yes           | GST0                   |                | 10.00                 | 10.00                |                       |                     |                    | PJE0000001       | 1                 |       |
      | 001 | 2  | IBONUS       |                          |              | SGD | 1.0           | 1   | 10         | Yes           | GST0                   |                | 10.00                 | 10.00                |                       |                     |                    | PJE0000001       | 1                 |       |
    Then user input Remarks in Draft state of Additional Payment by Recipient as as "<Remarks KEY>"
      | KEY | Internal Remark Code | Internal Remarks          | External Remark Code | External Remarks          |
      | 001 |                      | Internal Remarks for EMP1 |                      | External Remarks for EMP1 |
    Then user submits created voucher in Draft state of Additional Payment by Recipient
    Then user pulls out result in database into Excel file "Update Additional Vouchers Correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | File Name              | Sheet Name        | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select ADDITIONAL_PAYMENT_VCH_NO, DESCRIPTION, VOUCHER_TYPE, VOUCHER_DATE, PAYROLL_DATE, STATUS, RECIPIENT_CODE, TOTAL_NATURE_BEF_TAX, TOTAL_HOME_BEF_TAX, TOTAL_NATURE_AFT_TAX, TOTAL_HOME_AFT_TAX, IS_ADHOC_PAYMENT, IS_MEDICAL_CLAIM, OTHER_BOB_CODE, APPROVAL_REMARKSfrom PY_ADDITIONAL_PAYMENT where ADDITIONAL_PAYMENT_VCH_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                       | AddPaymentByRecepient1 | BeforeSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select ADDITIONAL_PAYMENT_VCH_NO, ADD_PMT_EMP_SER_SEQ_NO, STATUS, EMPLOYEE_CODE, WAGE_SERVICE_CODE, SALES_TAX_CODE, CURRENCY_CODE, EXCHANGE_RATE, PAYROLL_DATE, payroll.decode(QTY) QTY, payroll.decode(UNIT_PRICE) UNIT_PRICE, payroll.decode(NATURE_AMT) NATURE_AMT, INCLUSIVE_TAX, payroll.decode(NATURE_AMT_BEFORE_TAX) NATURE_AMT_BEFORE_TAX, payroll.decode(NATURE_AMT_AFTER_TAX) NATURE_AMT_AFTER_TAX, payroll.decode(HOME_AMT_BEFORE_TAX) HOME_AMT_BEFORE_TAX, payroll.decode(HOME_AMT_AFTER_TAX) HOME_AMT_AFTER_TAX,CLAIMABLE_AMT_BEFORE_TAX, CLAIMABLE_AMT_AFTER_TAX from PY_ADD_PMT_EMPLOYEE_SERVICE where ADDITIONAL_PAYMENT_VCH_NO = '@@#1#@@'                                                                           | AddPaymentByRecepient1 | BeforeSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select SOURCE_VOUCHER_CODE, EMP_PAYROLL_CATEGORY_CODE, SEQ_NO, EPC_COUNT from PY_ADDITIONAL_DEDUCTION_EPC where SOURCE_VOUCHER_CODE = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | AddPaymentByRecepient1 | BeforeSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select alloc.SRC_TRANSACTION_CODE, alloc.SRC_VOUCHER_NO, alloc.SRC_VOUCHER_TYPE, alloc.SRC_LINE_SEQ, alloc.ALLOC_VOUCHER_NO, alloc.ALLOC_PHASE_NO, alloc.ALLOC_LINE_NO, alloc.COST_ALLOCATION_NO,payroll.decode(pa.NATURE_AMT_BEFORE_TAX) NATURE_AMT_BEFORE_TAX, payroll.decode(pa.NATURE_AMT_AFTER_TAX) NATURE_AMT_AFTER_TAX, payroll.decode(pa.HOME_AMT_BEFORE_TAX) HOME_AMT_BEFORE_TAX, payroll.decode(pa.HOME_AMT_AFTER_TAX) HOME_AMT_AFTER_TAX,pa.CLAIMABLE_AMT_BEFORE_TAX, pa.CLAIMABLE_AMT_AFTER_TAX from PY_COST_ALLOCATION alloc join PY_ADD_PMT_EMPLOYEE_SERVICE pa on pa.ADDITIONAL_PAYMENT_VCH_NO = alloc.SRC_VOUCHER_NO and pa.ADD_PMT_EMP_SER_SEQ_NO = alloc.SRC_LINE_SEQ where pa.ADDITIONAL_PAYMENT_VCH_NO= '@@#1#@@' | AddPaymentByRecepient1 | BeforeSubmitAddPm | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Generate Cost Allocation Vouchers Correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                               | File Name              | Sheet Name        | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select COST_ALLOCATION_NO, COST_ALLOCATION_DATE, "TYPE", PROJECT_NO, CURRENCY_CODE, EXCH_RATE, SOURCE_TYPE, SOURCE_VOUCHER_NO, SOURCE_COMPANY_CODE from PJ_COST_ALC_HST_HDR where COST_ALLOCATION_NO in (select COST_ALLOCATION_NO from PY_COST_ALLOCATION where alloc.SRC_VOUCHER_NO = '@@#1#@@' )                                                                                         | AddPaymentByRecepient1 | BeforeSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select COST_ALLOCATION_NO, LINE_ITEM_NO, DT_TYPE, "TYPE", SERVICE_CODE, ADD_TOTAL_AMT, ADD_TOTAL_HOME_AMT, RED_TOTAL_AMT, RED_TOTAL_HOME_AMT from PJ_COST_ALC_HST_DET where COST_ALLOCATION_NO in (select COST_ALLOCATION_NO from PY_COST_ALLOCATION where alloc.SRC_VOUCHER_NO = '@@#1#@@'  )                                                                                              | AddPaymentByRecepient1 | BeforeSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select COST_ALLOCATION_NO, LINE_ITEM_NO, ALLOCATION_NO, ALLOCATION_TYPE, SOURCE_VOUCHER_NO, SOURCE_PHASE_NO, SOURCE_LINE_ITEM_NO, ALLOC_QTY, ALLOC_UNIT_COST, ADD_ALLOC_AMT, ADD_ALLOC_HOME_AMT, RED_ALLOC_AMT, RED_ALLOC_HOME_AMT from PJ_COST_ALC_HST_DET_ALLOC where COST_ALLOCATION_NO in (select COST_ALLOCATION_NO from PY_COST_ALLOCATION where alloc.SRC_VOUCHER_NO  = '@@#1#@@'  ) | AddPaymentByRecepient1 | BeforeSubmitAddPm | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update Project Estimation Actual Cost correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                 | File Name              | Sheet Name        | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select PROJECT_NO, PHASE_NO, COST_ITEM_NO, SERVICE_CODE, TOTAL_QTY_SHIPPED, NETT_QTY_SHIPPED, TOTAL_SHIPPED_COST, TOTAL_SHIPPED_COST_HOME, TOTAL_ACTUAL_COST, TOTAL_ACTUAL_COST_HOME, TOL_TOTAL_USED_HOME from PJ_EST_OST_CST_ITM = '@@#1#@@' | AddPaymentByRecepient1 | BeforeSubmitAddPm | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update GL correctly for the Allocation Vouchers" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                     | File Name              | Sheet Name        | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select MODULE_CODE, TRANSACTION_TYPE_CODE, SOURCE_VOUCHER_NO, CURRENCY_CODE, EXCH_RATE, GL_ACC_CODE, GL_ENTRY_TYPE, LINE_ITEM_NO, HOME_CREDIT, HOME_DEBIT, NATURE_CREDIT, NATURE_DEBIT from GL_LEDGER_SUMMARY where SOURCE_VOUCHER_NO = '@@#1#@@' | AddPaymentByRecepient1 | BeforeSubmitAddPm | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update Payslip correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | File Name              | Sheet Name        | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, STATUS, PAYSLIP_VOUCHER_DATE, EMPLOYEE_CODE, EMP_PAYROLL_CATEGORY_CODE, PAYSLIP_TYPE, payroll.decode(BASIC_SALARY) BASIC_SALARY, TOTAL_ADD_PYMT_BEFORE_TAX_AMT, TOTAL_ADD_PYMT_TAX_AMT, TOTAL_ADD_PYMT_AMT, ACTUAL_AW_AMT, ADDITIONAL_WAGE_SUBJ_CPF, ORDINARY_WAGE_SUBJ_CPF, EMPLOYER_CPF_CONTRIBUTIONS, EMPLOYEE_CPF_CONTRIBUTIONS, AW_TO_EMPLOYEE_CPF_AMT, OW_TO_EMPLOYEE_CPF_AMT, AW_TO_EMPLOYER_CPF_AMT, OW_TO_EMPLOYER_CPF_AMT, SKILL_DEVELOPMENT_LEVY, TOTAL_COMM_FUND_DONATION from PY_PAYSLIP where PY_GENERATION_VOUCHER_NO = '@@#1#@@' | AddPaymentByRecepient1 | BeforeSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, DONATION_CODE, CONTRIBUTION_AMT, ALLOC_MENDAKI_AMT, ALLOC_MOSQUE_AMT from PY_PAYSLIP_COM_FUND_DONATION where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                | AddPaymentByRecepient1 | BeforeSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, ADDITIONAL_PAYMENT_VCH_NO, SERVICE_CODE, ADD_PYMT_AMT, PROJECT_NO from PY_PAYSLIP_ADDITIONAL_PYMT where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                     | AddPaymentByRecepient1 | BeforeSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, ADDITIONAL_SUBJ_CPF_ADD from PY_PAYSLIP_ADDITIONAL_WAGE_CPF where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                           | AddPaymentByRecepient1 | BeforeSubmitAddPm | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update Personal Income infor correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | File Name              | Sheet Name        | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select EMPLOYEE_CODE, "YEAR", FROM_DATE, TO_DATE, AMOUNT, MOSQUE_BUILDING_FUND_AMT, DONATION_AMT, CPF_FUND_AMT, ADDITIONAL_SALARY_AMT, BONUS_AMT, DIRECTOR_FEE_AMT, OTHERS_AMT, GAINS_PROFIT_SHARE_OP_AMT, EXEMPT_REMISSION_AMT, BENEFITS_IN_KIND_AMT, GROSS_COMMISSION_AMT, PENSION_AMT, TRANSPORT_ALLOWANCE_AMT, ENTERTAINMENT_ALLOWANCE_AMT, OTHERS_ALLOWANCES_AMT, GRATUITY_AMT, COMPENSATION_BENEFITS_AMT, RETIREMENT_BENEFIT_92_AMT, RETIREMENT_BENEFIT_93_AMT, CONTRI_PENSION_OUT_SG_AMT, EXCESS_CONTRI_CPF_AMT, GAINS_PROFIT_FOR_S10_AMT, VALUE_BENEFITS_IN_KINDS_AMT, AW_TO_EMPLOYEE_CPF_AMT, OW_TO_EMPLOYEE_CPF_AMT, AW_TO_EMPLOYER_CPF_AMT, OW_TO_EMPLOYER_CPF_AMT, OW_EMPLOYEE_AMT, AW_EMPLOYEE_AMT, payroll.decode(BASIC_SALARY) BASIC_SALARY, payroll.decode(SALARY_AMT) SALARY_AMT, EMPLOYER_CPF_CONTRIBUTIONS, EMPLOYEE_CPF_CONTRIBUTIONS, OVER_CONTRIBUTION_AW_AMT, OVER_EMPLOYEE_AW_AMT, OVER_EMPLOYER_AW_AMT from PY_IR8A | AddPaymentByRecepient1 | BeforeSubmitAddPm |                        |         |                        |         |
    Then user pulls out result in database into Excel file "Update Additional Vouchers Correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | File Name              | Sheet Name       | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select ADDITIONAL_PAYMENT_VCH_NO, DESCRIPTION, VOUCHER_TYPE, VOUCHER_DATE, PAYROLL_DATE, STATUS, RECIPIENT_CODE, TOTAL_NATURE_BEF_TAX, TOTAL_HOME_BEF_TAX, TOTAL_NATURE_AFT_TAX, TOTAL_HOME_AFT_TAX, IS_ADHOC_PAYMENT, IS_MEDICAL_CLAIM, OTHER_BOB_CODE, APPROVAL_REMARKSfrom PY_ADDITIONAL_PAYMENT where ADDITIONAL_PAYMENT_VCH_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                       | AddPaymentByRecepient1 | AfterSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select ADDITIONAL_PAYMENT_VCH_NO, ADD_PMT_EMP_SER_SEQ_NO, STATUS, EMPLOYEE_CODE, WAGE_SERVICE_CODE, SALES_TAX_CODE, CURRENCY_CODE, EXCHANGE_RATE, PAYROLL_DATE, payroll.decode(QTY) QTY, payroll.decode(UNIT_PRICE) UNIT_PRICE, payroll.decode(NATURE_AMT) NATURE_AMT, INCLUSIVE_TAX, payroll.decode(NATURE_AMT_BEFORE_TAX) NATURE_AMT_BEFORE_TAX, payroll.decode(NATURE_AMT_AFTER_TAX) NATURE_AMT_AFTER_TAX, payroll.decode(HOME_AMT_BEFORE_TAX) HOME_AMT_BEFORE_TAX, payroll.decode(HOME_AMT_AFTER_TAX) HOME_AMT_AFTER_TAX,CLAIMABLE_AMT_BEFORE_TAX, CLAIMABLE_AMT_AFTER_TAX from PY_ADD_PMT_EMPLOYEE_SERVICE where ADDITIONAL_PAYMENT_VCH_NO = '@@#1#@@'                                                                           | AddPaymentByRecepient1 | AfterSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select SOURCE_VOUCHER_CODE, EMP_PAYROLL_CATEGORY_CODE, SEQ_NO, EPC_COUNT from PY_ADDITIONAL_DEDUCTION_EPC where SOURCE_VOUCHER_CODE = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | AddPaymentByRecepient1 | AfterSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select alloc.SRC_TRANSACTION_CODE, alloc.SRC_VOUCHER_NO, alloc.SRC_VOUCHER_TYPE, alloc.SRC_LINE_SEQ, alloc.ALLOC_VOUCHER_NO, alloc.ALLOC_PHASE_NO, alloc.ALLOC_LINE_NO, alloc.COST_ALLOCATION_NO,payroll.decode(pa.NATURE_AMT_BEFORE_TAX) NATURE_AMT_BEFORE_TAX, payroll.decode(pa.NATURE_AMT_AFTER_TAX) NATURE_AMT_AFTER_TAX, payroll.decode(pa.HOME_AMT_BEFORE_TAX) HOME_AMT_BEFORE_TAX, payroll.decode(pa.HOME_AMT_AFTER_TAX) HOME_AMT_AFTER_TAX,pa.CLAIMABLE_AMT_BEFORE_TAX, pa.CLAIMABLE_AMT_AFTER_TAX from PY_COST_ALLOCATION alloc join PY_ADD_PMT_EMPLOYEE_SERVICE pa on pa.ADDITIONAL_PAYMENT_VCH_NO = alloc.SRC_VOUCHER_NO and pa.ADD_PMT_EMP_SER_SEQ_NO = alloc.SRC_LINE_SEQ where pa.ADDITIONAL_PAYMENT_VCH_NO= '@@#1#@@' | AddPaymentByRecepient1 | AfterSubmitAddPm | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Generate Cost Allocation Vouchers Correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                               | File Name              | Sheet Name       | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select COST_ALLOCATION_NO, COST_ALLOCATION_DATE, "TYPE", PROJECT_NO, CURRENCY_CODE, EXCH_RATE, SOURCE_TYPE, SOURCE_VOUCHER_NO, SOURCE_COMPANY_CODE from PJ_COST_ALC_HST_HDR where COST_ALLOCATION_NO in (select COST_ALLOCATION_NO from PY_COST_ALLOCATION where alloc.SRC_VOUCHER_NO = '@@#1#@@' )                                                                                         | AddPaymentByRecepient1 | AfterSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select COST_ALLOCATION_NO, LINE_ITEM_NO, DT_TYPE, "TYPE", SERVICE_CODE, ADD_TOTAL_AMT, ADD_TOTAL_HOME_AMT, RED_TOTAL_AMT, RED_TOTAL_HOME_AMT from PJ_COST_ALC_HST_DET where COST_ALLOCATION_NO in (select COST_ALLOCATION_NO from PY_COST_ALLOCATION where alloc.SRC_VOUCHER_NO = '@@#1#@@'  )                                                                                              | AddPaymentByRecepient1 | AfterSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select COST_ALLOCATION_NO, LINE_ITEM_NO, ALLOCATION_NO, ALLOCATION_TYPE, SOURCE_VOUCHER_NO, SOURCE_PHASE_NO, SOURCE_LINE_ITEM_NO, ALLOC_QTY, ALLOC_UNIT_COST, ADD_ALLOC_AMT, ADD_ALLOC_HOME_AMT, RED_ALLOC_AMT, RED_ALLOC_HOME_AMT from PJ_COST_ALC_HST_DET_ALLOC where COST_ALLOCATION_NO in (select COST_ALLOCATION_NO from PY_COST_ALLOCATION where alloc.SRC_VOUCHER_NO  = '@@#1#@@'  ) | AddPaymentByRecepient1 | AfterSubmitAddPm | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update Project Estimation Actual Cost correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                 | File Name              | Sheet Name       | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select PROJECT_NO, PHASE_NO, COST_ITEM_NO, SERVICE_CODE, TOTAL_QTY_SHIPPED, NETT_QTY_SHIPPED, TOTAL_SHIPPED_COST, TOTAL_SHIPPED_COST_HOME, TOTAL_ACTUAL_COST, TOTAL_ACTUAL_COST_HOME, TOL_TOTAL_USED_HOME from PJ_EST_OST_CST_ITM = '@@#1#@@' | AddPaymentByRecepient1 | AfterSubmitAddPm | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update GL correctly for the Allocation Vouchers" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                     | File Name              | Sheet Name       | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select MODULE_CODE, TRANSACTION_TYPE_CODE, SOURCE_VOUCHER_NO, CURRENCY_CODE, EXCH_RATE, GL_ACC_CODE, GL_ENTRY_TYPE, LINE_ITEM_NO, HOME_CREDIT, HOME_DEBIT, NATURE_CREDIT, NATURE_DEBIT from GL_LEDGER_SUMMARY where SOURCE_VOUCHER_NO = '@@#1#@@' | AddPaymentByRecepient1 | AfterSubmitAddPm | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update Payslip correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | File Name              | Sheet Name       | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, STATUS, PAYSLIP_VOUCHER_DATE, EMPLOYEE_CODE, EMP_PAYROLL_CATEGORY_CODE, PAYSLIP_TYPE, payroll.decode(BASIC_SALARY) BASIC_SALARY, TOTAL_ADD_PYMT_BEFORE_TAX_AMT, TOTAL_ADD_PYMT_TAX_AMT, TOTAL_ADD_PYMT_AMT, ACTUAL_AW_AMT, ADDITIONAL_WAGE_SUBJ_CPF, ORDINARY_WAGE_SUBJ_CPF, EMPLOYER_CPF_CONTRIBUTIONS, EMPLOYEE_CPF_CONTRIBUTIONS, AW_TO_EMPLOYEE_CPF_AMT, OW_TO_EMPLOYEE_CPF_AMT, AW_TO_EMPLOYER_CPF_AMT, OW_TO_EMPLOYER_CPF_AMT, SKILL_DEVELOPMENT_LEVY, TOTAL_COMM_FUND_DONATION from PY_PAYSLIP where PY_GENERATION_VOUCHER_NO = '@@#1#@@' | AddPaymentByRecepient1 | AfterSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, DONATION_CODE, CONTRIBUTION_AMT, ALLOC_MENDAKI_AMT, ALLOC_MOSQUE_AMT from PY_PAYSLIP_COM_FUND_DONATION where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                | AddPaymentByRecepient1 | AfterSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, ADDITIONAL_PAYMENT_VCH_NO, SERVICE_CODE, ADD_PYMT_AMT, PROJECT_NO from PY_PAYSLIP_ADDITIONAL_PYMT where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                     | AddPaymentByRecepient1 | AfterSubmitAddPm | Add Payment Voucher No |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, ADDITIONAL_SUBJ_CPF_ADD from PY_PAYSLIP_ADDITIONAL_WAGE_CPF where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                           | AddPaymentByRecepient1 | AfterSubmitAddPm | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update Personal Income infor correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | File Name              | Sheet Name       | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select EMPLOYEE_CODE, "YEAR", FROM_DATE, TO_DATE, AMOUNT, MOSQUE_BUILDING_FUND_AMT, DONATION_AMT, CPF_FUND_AMT, ADDITIONAL_SALARY_AMT, BONUS_AMT, DIRECTOR_FEE_AMT, OTHERS_AMT, GAINS_PROFIT_SHARE_OP_AMT, EXEMPT_REMISSION_AMT, BENEFITS_IN_KIND_AMT, GROSS_COMMISSION_AMT, PENSION_AMT, TRANSPORT_ALLOWANCE_AMT, ENTERTAINMENT_ALLOWANCE_AMT, OTHERS_ALLOWANCES_AMT, GRATUITY_AMT, COMPENSATION_BENEFITS_AMT, RETIREMENT_BENEFIT_92_AMT, RETIREMENT_BENEFIT_93_AMT, CONTRI_PENSION_OUT_SG_AMT, EXCESS_CONTRI_CPF_AMT, GAINS_PROFIT_FOR_S10_AMT, VALUE_BENEFITS_IN_KINDS_AMT, AW_TO_EMPLOYEE_CPF_AMT, OW_TO_EMPLOYEE_CPF_AMT, AW_TO_EMPLOYER_CPF_AMT, OW_TO_EMPLOYER_CPF_AMT, OW_EMPLOYEE_AMT, AW_EMPLOYEE_AMT, payroll.decode(BASIC_SALARY) BASIC_SALARY, payroll.decode(SALARY_AMT) SALARY_AMT, EMPLOYER_CPF_CONTRIBUTIONS, EMPLOYEE_CPF_CONTRIBUTIONS, OVER_CONTRIBUTION_AW_AMT, OVER_EMPLOYEE_AW_AMT, OVER_EMPLOYER_AW_AMT from PY_IR8A | AddPaymentByRecepient1 | AfterSubmitAddPm |                        |         |                        |         |

    Examples: 
      | Login User KEY | Module Config KEY | Additional Payment KEY | Recipient KEY | Wage Services KEY | Remarks KEY | Pullout Excel KEY | DATABASE KEY |
      | 001            |                   | 001                    | 001           | 001               | 001         | 001               | 001          |

  Scenario Outline: Generates payslip and submit
    Given user logins to Task Hub as "<Login User KEY>"
      | KEY | User Name | Password | Company |
      | 001 | vincent1  | taskhub  | (TRG6)  |
    Given user changes database connection as "<DATABASE KEY>"
      | KEY | JDBC_DRIVER               | IP_SERVER   | SERVER_PORT | DB_NAME  | USER_NAME | PASS_WORD |
      | 001 | com.ibm.db2.jcc.DB2Driver | 172.18.0.10 | 50000       | GENMAIN6 | db2admin  | Taskhub1  |
    When user generates payslip for Additional Payment as "<Generation KEY>"
      | KEY | Payroll GL Posting Date | Year | Month | Payment Cycle Code | Payment Cycle No | Generate Payslip for advancement | Generate Payslip By       | EPC   | Submit |
      | 001 | 05/08/2016              | 2016 | 8     | AMONTHLY           | 1st              | N                                | Employee Payroll Category | DPEPC | Y      |
    Then user pulls out result in database into Excel file "Update Additional Vouchers Correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | File Name              | Sheet Name      | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select ADDITIONAL_PAYMENT_VCH_NO, DESCRIPTION, VOUCHER_TYPE, VOUCHER_DATE, PAYROLL_DATE, STATUS, RECIPIENT_CODE, TOTAL_NATURE_BEF_TAX, TOTAL_HOME_BEF_TAX, TOTAL_NATURE_AFT_TAX, TOTAL_HOME_AFT_TAX, IS_ADHOC_PAYMENT, IS_MEDICAL_CLAIM, OTHER_BOB_CODE, APPROVAL_REMARKSfrom PY_ADDITIONAL_PAYMENT where ADDITIONAL_PAYMENT_VCH_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                       | AddPaymentByRecepient1 | AfterPayrollGen | Add Payment Voucher No |         |                        |         |
      | 001 | select ADDITIONAL_PAYMENT_VCH_NO, ADD_PMT_EMP_SER_SEQ_NO, STATUS, EMPLOYEE_CODE, WAGE_SERVICE_CODE, SALES_TAX_CODE, CURRENCY_CODE, EXCHANGE_RATE, PAYROLL_DATE, payroll.decode(QTY) QTY, payroll.decode(UNIT_PRICE) UNIT_PRICE, payroll.decode(NATURE_AMT) NATURE_AMT, INCLUSIVE_TAX, payroll.decode(NATURE_AMT_BEFORE_TAX) NATURE_AMT_BEFORE_TAX, payroll.decode(NATURE_AMT_AFTER_TAX) NATURE_AMT_AFTER_TAX, payroll.decode(HOME_AMT_BEFORE_TAX) HOME_AMT_BEFORE_TAX, payroll.decode(HOME_AMT_AFTER_TAX) HOME_AMT_AFTER_TAX,CLAIMABLE_AMT_BEFORE_TAX, CLAIMABLE_AMT_AFTER_TAX from PY_ADD_PMT_EMPLOYEE_SERVICE where ADDITIONAL_PAYMENT_VCH_NO = '@@#1#@@'                                                                           | AddPaymentByRecepient1 | AfterPayrollGen | Add Payment Voucher No |         |                        |         |
      | 001 | select SOURCE_VOUCHER_CODE, EMP_PAYROLL_CATEGORY_CODE, SEQ_NO, EPC_COUNT from PY_ADDITIONAL_DEDUCTION_EPC where SOURCE_VOUCHER_CODE = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | AddPaymentByRecepient1 | AfterPayrollGen | Add Payment Voucher No |         |                        |         |
      | 001 | select alloc.SRC_TRANSACTION_CODE, alloc.SRC_VOUCHER_NO, alloc.SRC_VOUCHER_TYPE, alloc.SRC_LINE_SEQ, alloc.ALLOC_VOUCHER_NO, alloc.ALLOC_PHASE_NO, alloc.ALLOC_LINE_NO, alloc.COST_ALLOCATION_NO,payroll.decode(pa.NATURE_AMT_BEFORE_TAX) NATURE_AMT_BEFORE_TAX, payroll.decode(pa.NATURE_AMT_AFTER_TAX) NATURE_AMT_AFTER_TAX, payroll.decode(pa.HOME_AMT_BEFORE_TAX) HOME_AMT_BEFORE_TAX, payroll.decode(pa.HOME_AMT_AFTER_TAX) HOME_AMT_AFTER_TAX,pa.CLAIMABLE_AMT_BEFORE_TAX, pa.CLAIMABLE_AMT_AFTER_TAX from PY_COST_ALLOCATION alloc join PY_ADD_PMT_EMPLOYEE_SERVICE pa on pa.ADDITIONAL_PAYMENT_VCH_NO = alloc.SRC_VOUCHER_NO and pa.ADD_PMT_EMP_SER_SEQ_NO = alloc.SRC_LINE_SEQ where pa.ADDITIONAL_PAYMENT_VCH_NO= '@@#1#@@' | AddPaymentByRecepient1 | AfterPayrollGen | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Generate Cost Allocation Vouchers Correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                               | File Name              | Sheet Name      | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select COST_ALLOCATION_NO, COST_ALLOCATION_DATE, "TYPE", PROJECT_NO, CURRENCY_CODE, EXCH_RATE, SOURCE_TYPE, SOURCE_VOUCHER_NO, SOURCE_COMPANY_CODE from PJ_COST_ALC_HST_HDR where COST_ALLOCATION_NO in (select COST_ALLOCATION_NO from PY_COST_ALLOCATION where alloc.SRC_VOUCHER_NO = '@@#1#@@' )                                                                                         | AddPaymentByRecepient1 | AfterPayrollGen | Add Payment Voucher No |         |                        |         |
      | 001 | select COST_ALLOCATION_NO, LINE_ITEM_NO, DT_TYPE, "TYPE", SERVICE_CODE, ADD_TOTAL_AMT, ADD_TOTAL_HOME_AMT, RED_TOTAL_AMT, RED_TOTAL_HOME_AMT from PJ_COST_ALC_HST_DET where COST_ALLOCATION_NO in (select COST_ALLOCATION_NO from PY_COST_ALLOCATION where alloc.SRC_VOUCHER_NO = '@@#1#@@'  )                                                                                              | AddPaymentByRecepient1 | AfterPayrollGen | Add Payment Voucher No |         |                        |         |
      | 001 | select COST_ALLOCATION_NO, LINE_ITEM_NO, ALLOCATION_NO, ALLOCATION_TYPE, SOURCE_VOUCHER_NO, SOURCE_PHASE_NO, SOURCE_LINE_ITEM_NO, ALLOC_QTY, ALLOC_UNIT_COST, ADD_ALLOC_AMT, ADD_ALLOC_HOME_AMT, RED_ALLOC_AMT, RED_ALLOC_HOME_AMT from PJ_COST_ALC_HST_DET_ALLOC where COST_ALLOCATION_NO in (select COST_ALLOCATION_NO from PY_COST_ALLOCATION where alloc.SRC_VOUCHER_NO  = '@@#1#@@'  ) | AddPaymentByRecepient1 | AfterPayrollGen | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update Project Estimation Actual Cost correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                 | File Name              | Sheet Name      | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select PROJECT_NO, PHASE_NO, COST_ITEM_NO, SERVICE_CODE, TOTAL_QTY_SHIPPED, NETT_QTY_SHIPPED, TOTAL_SHIPPED_COST, TOTAL_SHIPPED_COST_HOME, TOTAL_ACTUAL_COST, TOTAL_ACTUAL_COST_HOME, TOL_TOTAL_USED_HOME from PJ_EST_OST_CST_ITM = '@@#1#@@' | AddPaymentByRecepient1 | AfterPayrollGen | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update GL correctly for the Allocation Vouchers" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                     | File Name              | Sheet Name      | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select MODULE_CODE, TRANSACTION_TYPE_CODE, SOURCE_VOUCHER_NO, CURRENCY_CODE, EXCH_RATE, GL_ACC_CODE, GL_ENTRY_TYPE, LINE_ITEM_NO, HOME_CREDIT, HOME_DEBIT, NATURE_CREDIT, NATURE_DEBIT from GL_LEDGER_SUMMARY where SOURCE_VOUCHER_NO = '@@#1#@@' | AddPaymentByRecepient1 | AfterPayrollGen | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update Payslip correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | File Name              | Sheet Name      | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, STATUS, PAYSLIP_VOUCHER_DATE, EMPLOYEE_CODE, EMP_PAYROLL_CATEGORY_CODE, PAYSLIP_TYPE, payroll.decode(BASIC_SALARY) BASIC_SALARY, TOTAL_ADD_PYMT_BEFORE_TAX_AMT, TOTAL_ADD_PYMT_TAX_AMT, TOTAL_ADD_PYMT_AMT, ACTUAL_AW_AMT, ADDITIONAL_WAGE_SUBJ_CPF, ORDINARY_WAGE_SUBJ_CPF, EMPLOYER_CPF_CONTRIBUTIONS, EMPLOYEE_CPF_CONTRIBUTIONS, AW_TO_EMPLOYEE_CPF_AMT, OW_TO_EMPLOYEE_CPF_AMT, AW_TO_EMPLOYER_CPF_AMT, OW_TO_EMPLOYER_CPF_AMT, SKILL_DEVELOPMENT_LEVY, TOTAL_COMM_FUND_DONATION from PY_PAYSLIP where PY_GENERATION_VOUCHER_NO = '@@#1#@@' | AddPaymentByRecepient1 | AfterPayrollGen | Add Payment Voucher No |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, DONATION_CODE, CONTRIBUTION_AMT, ALLOC_MENDAKI_AMT, ALLOC_MOSQUE_AMT from PY_PAYSLIP_COM_FUND_DONATION where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                | AddPaymentByRecepient1 | AfterPayrollGen | Add Payment Voucher No |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, ADDITIONAL_PAYMENT_VCH_NO, SERVICE_CODE, ADD_PYMT_AMT, PROJECT_NO from PY_PAYSLIP_ADDITIONAL_PYMT where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                     | AddPaymentByRecepient1 | AfterPayrollGen | Add Payment Voucher No |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, ADDITIONAL_SUBJ_CPF_ADD from PY_PAYSLIP_ADDITIONAL_WAGE_CPF where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                           | AddPaymentByRecepient1 | AfterPayrollGen | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update Personal Income infor correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | File Name              | Sheet Name      | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select EMPLOYEE_CODE, "YEAR", FROM_DATE, TO_DATE, AMOUNT, MOSQUE_BUILDING_FUND_AMT, DONATION_AMT, CPF_FUND_AMT, ADDITIONAL_SALARY_AMT, BONUS_AMT, DIRECTOR_FEE_AMT, OTHERS_AMT, GAINS_PROFIT_SHARE_OP_AMT, EXEMPT_REMISSION_AMT, BENEFITS_IN_KIND_AMT, GROSS_COMMISSION_AMT, PENSION_AMT, TRANSPORT_ALLOWANCE_AMT, ENTERTAINMENT_ALLOWANCE_AMT, OTHERS_ALLOWANCES_AMT, GRATUITY_AMT, COMPENSATION_BENEFITS_AMT, RETIREMENT_BENEFIT_92_AMT, RETIREMENT_BENEFIT_93_AMT, CONTRI_PENSION_OUT_SG_AMT, EXCESS_CONTRI_CPF_AMT, GAINS_PROFIT_FOR_S10_AMT, VALUE_BENEFITS_IN_KINDS_AMT, AW_TO_EMPLOYEE_CPF_AMT, OW_TO_EMPLOYEE_CPF_AMT, AW_TO_EMPLOYER_CPF_AMT, OW_TO_EMPLOYER_CPF_AMT, OW_EMPLOYEE_AMT, AW_EMPLOYEE_AMT, payroll.decode(BASIC_SALARY) BASIC_SALARY, payroll.decode(SALARY_AMT) SALARY_AMT, EMPLOYER_CPF_CONTRIBUTIONS, EMPLOYEE_CPF_CONTRIBUTIONS, OVER_CONTRIBUTION_AW_AMT, OVER_EMPLOYEE_AW_AMT, OVER_EMPLOYER_AW_AMT from PY_IR8A | AddPaymentByRecepient1 | AfterPayrollGen |                        |         |                        |         |
    And user submits payslip for Additional Payment as "<Payslip KEY>"
      | KEY | Voucher No               |
      | 001 | @CreatedGenerateVoucher@ |
    Then user pulls out result in database into Excel file "Update Additional Vouchers Correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | File Name              | Sheet Name      | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select ADDITIONAL_PAYMENT_VCH_NO, DESCRIPTION, VOUCHER_TYPE, VOUCHER_DATE, PAYROLL_DATE, STATUS, RECIPIENT_CODE, TOTAL_NATURE_BEF_TAX, TOTAL_HOME_BEF_TAX, TOTAL_NATURE_AFT_TAX, TOTAL_HOME_AFT_TAX, IS_ADHOC_PAYMENT, IS_MEDICAL_CLAIM, OTHER_BOB_CODE, APPROVAL_REMARKSfrom PY_ADDITIONAL_PAYMENT where ADDITIONAL_PAYMENT_VCH_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                       | AddPaymentByRecepient1 | AfterPayslipSub | Add Payment Voucher No |         |                        |         |
      | 001 | select ADDITIONAL_PAYMENT_VCH_NO, ADD_PMT_EMP_SER_SEQ_NO, STATUS, EMPLOYEE_CODE, WAGE_SERVICE_CODE, SALES_TAX_CODE, CURRENCY_CODE, EXCHANGE_RATE, PAYROLL_DATE, payroll.decode(QTY) QTY, payroll.decode(UNIT_PRICE) UNIT_PRICE, payroll.decode(NATURE_AMT) NATURE_AMT, INCLUSIVE_TAX, payroll.decode(NATURE_AMT_BEFORE_TAX) NATURE_AMT_BEFORE_TAX, payroll.decode(NATURE_AMT_AFTER_TAX) NATURE_AMT_AFTER_TAX, payroll.decode(HOME_AMT_BEFORE_TAX) HOME_AMT_BEFORE_TAX, payroll.decode(HOME_AMT_AFTER_TAX) HOME_AMT_AFTER_TAX,CLAIMABLE_AMT_BEFORE_TAX, CLAIMABLE_AMT_AFTER_TAX from PY_ADD_PMT_EMPLOYEE_SERVICE where ADDITIONAL_PAYMENT_VCH_NO = '@@#1#@@'                                                                           | AddPaymentByRecepient1 | AfterPayslipSub | Add Payment Voucher No |         |                        |         |
      | 001 | select SOURCE_VOUCHER_CODE, EMP_PAYROLL_CATEGORY_CODE, SEQ_NO, EPC_COUNT from PY_ADDITIONAL_DEDUCTION_EPC where SOURCE_VOUCHER_CODE = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | AddPaymentByRecepient1 | AfterPayslipSub | Add Payment Voucher No |         |                        |         |
      | 001 | select alloc.SRC_TRANSACTION_CODE, alloc.SRC_VOUCHER_NO, alloc.SRC_VOUCHER_TYPE, alloc.SRC_LINE_SEQ, alloc.ALLOC_VOUCHER_NO, alloc.ALLOC_PHASE_NO, alloc.ALLOC_LINE_NO, alloc.COST_ALLOCATION_NO,payroll.decode(pa.NATURE_AMT_BEFORE_TAX) NATURE_AMT_BEFORE_TAX, payroll.decode(pa.NATURE_AMT_AFTER_TAX) NATURE_AMT_AFTER_TAX, payroll.decode(pa.HOME_AMT_BEFORE_TAX) HOME_AMT_BEFORE_TAX, payroll.decode(pa.HOME_AMT_AFTER_TAX) HOME_AMT_AFTER_TAX,pa.CLAIMABLE_AMT_BEFORE_TAX, pa.CLAIMABLE_AMT_AFTER_TAX from PY_COST_ALLOCATION alloc join PY_ADD_PMT_EMPLOYEE_SERVICE pa on pa.ADDITIONAL_PAYMENT_VCH_NO = alloc.SRC_VOUCHER_NO and pa.ADD_PMT_EMP_SER_SEQ_NO = alloc.SRC_LINE_SEQ where pa.ADDITIONAL_PAYMENT_VCH_NO= '@@#1#@@' | AddPaymentByRecepient1 | AfterPayslipSub | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Generate Cost Allocation Vouchers Correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                               | File Name              | Sheet Name      | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select COST_ALLOCATION_NO, COST_ALLOCATION_DATE, "TYPE", PROJECT_NO, CURRENCY_CODE, EXCH_RATE, SOURCE_TYPE, SOURCE_VOUCHER_NO, SOURCE_COMPANY_CODE from PJ_COST_ALC_HST_HDR where COST_ALLOCATION_NO in (select COST_ALLOCATION_NO from PY_COST_ALLOCATION where alloc.SRC_VOUCHER_NO = '@@#1#@@' )                                                                                         | AddPaymentByRecepient1 | AfterPayslipSub | Add Payment Voucher No |         |                        |         |
      | 001 | select COST_ALLOCATION_NO, LINE_ITEM_NO, DT_TYPE, "TYPE", SERVICE_CODE, ADD_TOTAL_AMT, ADD_TOTAL_HOME_AMT, RED_TOTAL_AMT, RED_TOTAL_HOME_AMT from PJ_COST_ALC_HST_DET where COST_ALLOCATION_NO in (select COST_ALLOCATION_NO from PY_COST_ALLOCATION where alloc.SRC_VOUCHER_NO = '@@#1#@@'  )                                                                                              | AddPaymentByRecepient1 | AfterPayslipSub | Add Payment Voucher No |         |                        |         |
      | 001 | select COST_ALLOCATION_NO, LINE_ITEM_NO, ALLOCATION_NO, ALLOCATION_TYPE, SOURCE_VOUCHER_NO, SOURCE_PHASE_NO, SOURCE_LINE_ITEM_NO, ALLOC_QTY, ALLOC_UNIT_COST, ADD_ALLOC_AMT, ADD_ALLOC_HOME_AMT, RED_ALLOC_AMT, RED_ALLOC_HOME_AMT from PJ_COST_ALC_HST_DET_ALLOC where COST_ALLOCATION_NO in (select COST_ALLOCATION_NO from PY_COST_ALLOCATION where alloc.SRC_VOUCHER_NO  = '@@#1#@@'  ) | AddPaymentByRecepient1 | AfterPayslipSub | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update Project Estimation Actual Cost correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                 | File Name              | Sheet Name      | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select PROJECT_NO, PHASE_NO, COST_ITEM_NO, SERVICE_CODE, TOTAL_QTY_SHIPPED, NETT_QTY_SHIPPED, TOTAL_SHIPPED_COST, TOTAL_SHIPPED_COST_HOME, TOTAL_ACTUAL_COST, TOTAL_ACTUAL_COST_HOME, TOL_TOTAL_USED_HOME from PJ_EST_OST_CST_ITM = '@@#1#@@' | AddPaymentByRecepient1 | AfterPayslipSub | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update GL correctly for the Allocation Vouchers" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                     | File Name              | Sheet Name      | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select MODULE_CODE, TRANSACTION_TYPE_CODE, SOURCE_VOUCHER_NO, CURRENCY_CODE, EXCH_RATE, GL_ACC_CODE, GL_ENTRY_TYPE, LINE_ITEM_NO, HOME_CREDIT, HOME_DEBIT, NATURE_CREDIT, NATURE_DEBIT from GL_LEDGER_SUMMARY where SOURCE_VOUCHER_NO = '@@#1#@@' | AddPaymentByRecepient1 | AfterPayslipSub | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update Payslip correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | File Name              | Sheet Name      | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, STATUS, PAYSLIP_VOUCHER_DATE, EMPLOYEE_CODE, EMP_PAYROLL_CATEGORY_CODE, PAYSLIP_TYPE, payroll.decode(BASIC_SALARY) BASIC_SALARY, TOTAL_ADD_PYMT_BEFORE_TAX_AMT, TOTAL_ADD_PYMT_TAX_AMT, TOTAL_ADD_PYMT_AMT, ACTUAL_AW_AMT, ADDITIONAL_WAGE_SUBJ_CPF, ORDINARY_WAGE_SUBJ_CPF, EMPLOYER_CPF_CONTRIBUTIONS, EMPLOYEE_CPF_CONTRIBUTIONS, AW_TO_EMPLOYEE_CPF_AMT, OW_TO_EMPLOYEE_CPF_AMT, AW_TO_EMPLOYER_CPF_AMT, OW_TO_EMPLOYER_CPF_AMT, SKILL_DEVELOPMENT_LEVY, TOTAL_COMM_FUND_DONATION from PY_PAYSLIP where PY_GENERATION_VOUCHER_NO = '@@#1#@@' | AddPaymentByRecepient1 | AfterPayslipSub | Add Payment Voucher No |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, DONATION_CODE, CONTRIBUTION_AMT, ALLOC_MENDAKI_AMT, ALLOC_MOSQUE_AMT from PY_PAYSLIP_COM_FUND_DONATION where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                | AddPaymentByRecepient1 | AfterPayslipSub | Add Payment Voucher No |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, ADDITIONAL_PAYMENT_VCH_NO, SERVICE_CODE, ADD_PYMT_AMT, PROJECT_NO from PY_PAYSLIP_ADDITIONAL_PYMT where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                     | AddPaymentByRecepient1 | AfterPayslipSub | Add Payment Voucher No |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO, PAYSLIP_VOUCHER_NO, ADDITIONAL_SUBJ_CPF_ADD from PY_PAYSLIP_ADDITIONAL_WAGE_CPF where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                           | AddPaymentByRecepient1 | AfterPayslipSub | Add Payment Voucher No |         |                        |         |
    Then user pulls out result in database into Excel file "Update Personal Income infor correctly" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | File Name              | Sheet Name      | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select EMPLOYEE_CODE, "YEAR", FROM_DATE, TO_DATE, AMOUNT, MOSQUE_BUILDING_FUND_AMT, DONATION_AMT, CPF_FUND_AMT, ADDITIONAL_SALARY_AMT, BONUS_AMT, DIRECTOR_FEE_AMT, OTHERS_AMT, GAINS_PROFIT_SHARE_OP_AMT, EXEMPT_REMISSION_AMT, BENEFITS_IN_KIND_AMT, GROSS_COMMISSION_AMT, PENSION_AMT, TRANSPORT_ALLOWANCE_AMT, ENTERTAINMENT_ALLOWANCE_AMT, OTHERS_ALLOWANCES_AMT, GRATUITY_AMT, COMPENSATION_BENEFITS_AMT, RETIREMENT_BENEFIT_92_AMT, RETIREMENT_BENEFIT_93_AMT, CONTRI_PENSION_OUT_SG_AMT, EXCESS_CONTRI_CPF_AMT, GAINS_PROFIT_FOR_S10_AMT, VALUE_BENEFITS_IN_KINDS_AMT, AW_TO_EMPLOYEE_CPF_AMT, OW_TO_EMPLOYEE_CPF_AMT, AW_TO_EMPLOYER_CPF_AMT, OW_TO_EMPLOYER_CPF_AMT, OW_EMPLOYEE_AMT, AW_EMPLOYEE_AMT, payroll.decode(BASIC_SALARY) BASIC_SALARY, payroll.decode(SALARY_AMT) SALARY_AMT, EMPLOYER_CPF_CONTRIBUTIONS, EMPLOYEE_CPF_CONTRIBUTIONS, OVER_CONTRIBUTION_AW_AMT, OVER_EMPLOYEE_AW_AMT, OVER_EMPLOYER_AW_AMT from PY_IR8A | AddPaymentByRecepient1 | AfterPayslipSub |                        |         |                        |         |
    Then user compares pulled out Excel file with Reference Excel file as "<Compare KEY>"
      | KEY | Output File Name       | Reference File Name    | Checksum Difference |
      | 001 | AddPaymentByRecepient1 | AddPaymentByRecepient1 | 1252                |

    Examples: 
      | Login User KEY | DATABASE KEY | Pullout Excel KEY | Generation KEY | Payslip KEY | Compare KEY |
      | 001            | 001          | 001               | 001            | 001         | 001         |
