@vincent @additional_payment_by_recipient_1
Feature: Test for Payroll Additional Payment Standard
  Test-condition:
  Enable Employee Payroll Security - Yes
  Enable Inclusive Sales Tax - Yes
  Overwrite Sales Tax Code - Yes
  Enable Approval For Additional Payment - No

  Scenario: Clear data for AddPayment Voucher, Payroll Generation, Payroll Payslip
    Given user access DB "jdbc:db2://172.18.0.10:50000/GENMAIN6" with id "db2admin" and password "Taskhub1"
    Given Data is clear as in "AddPayment_ClearSQL.xls"

  Scenario Outline: Create for Payroll Additional Payment Standard
    Given user logins to Task Hub as "<Login User KEY>"
      | KEY | User Name | Password | Company |
      | 001 | vincent1  | taskhub  | (TRG6)  |
    Given user changes database connection as "<DATABASE KEY>"
      | KEY | JDBC_DRIVER               | IP_SERVER   | SERVER_PORT | DB_NAME  | USER_NAME | PASS_WORD |
      | 001 | com.ibm.db2.jcc.DB2Driver | 172.18.0.10 | 50000       | GENMAIN6 | db2admin  | Taskhub1  |
    When user navigates to "Maintenance Setup>Module Config>Module Config" screen
    Then user changes Module Config as "<Module Config KEY>"
      | KEY | Module Section                                 | Module Name                                                                                                                   | Config Type 1 | Config Value 1 | Config Type 2 | Config Value 2 |
      | 001 | Payroll>Payroll                                | Enable Inclusive Sales Tax                                                                                                    | Radio         | Yes            |               |                |
      | 001 | Payroll>Payroll                                | Enable allocate Additional Payment to different Line Item                                                                     | Radio         | No             |               |                |
      | 001 | Payroll>Payroll                                | Overwrite Sales Tax Code                                                                                                      | Radio         | Yes            |               |                |
      | 001 | Payroll>Payroll                                | Enable Approval for Additional Payment (By Recipient).                                                                        | Radio         | No             |               |                |
      | 001 | Project Costing>Project Quotation & Estimation | Disable GL Entries For Recognition                                                                                            | Radio         | Yes            |               |                |
      | 001 | Project Costing>Project Costing                | Enable to Post Project Cost to Expense GLAN/Revenue GLAN of Cost Item instead of Project WIP GLAN (exclude Payroll Timesheet) | Radio         | Yes            |               |                |
      | 002 | Payroll>Payroll                                | Enable allocate Additional Payment to different Line Item                                                                     | Radio         | Yes            |               |                |
    When user navigates to "Processing>Payroll>Additional Payment" screen
    Then page header shouble be "Additional Payment"
    When user creates new voucher in Draft state of Additional Payment by Recipient
    Then all information in Draft state of Additional Payment by Recipient should be pulled out as "<Additional Payment KEY>"
      | KEY | Voucher No | Voucher Type | Voucher Date | Description |
      | 001 | @NotBlank@ | By Recipient |              | @Blank@     |
    Then user inputs data for new voucher in Draft state of Additional Payment by Recipient as "<Recipient KEY>"
      | KEY | Description               | Voucher Date | Recipients Code | Recipients Name | Payroll Date  |
      | 001 | Test for Add payment by R |              | EMP1            |                 | @CurrentDate@ |
    Then user add data for Wage Services in Draft state of Additional Payment by Recipient as "<Wage Services KEY>"
      | KEY | No | Wage Service | Wage Service Description | Voucher Date | Ccy | Exchange Rate | Qty | Unit Price | Inclusive Tax | Sales Tax Code Default | Sales Tax Edit | Nature Amt Before Tax | Nature Amt After Tax | Commission Start Date | Commission End Date | Monthly Commission | Alloc Voucher No | Phase Sequence No | LI No |
      | 001 | 1  | ISALARY      |                          |              | SGD | 1.0           | 1   | 10         | Yes           | GST0                   |                | 10.00                 | 10.00                |                       |                     |                    | PJE0000001       | 1                 |       |
      | 001 | 2  | IBONUS       |                          |              | SGD | 1.0           | 1   | 10         | Yes           | GST0                   |                | 10.00                 | 10.00                |                       |                     |                    | PJE0000001       | 1                 |       |
      | 001 | 3  | ICOMMISSION  |                          |              | SGD | 1.0           | 1   | 20         | Yes           | GST0                   |                | 20.00                 | 20.00                | 04/08/2016            | 04/08/2016          | No                 | PJE0000001       | 1                 |       |
      | 001 | 4  | IDIRECTFEE   |                          |              | SGD | 1.0           | 1   | 30         | Yes           | GST0                   |                | 30.00                 | 30.00                |                       |                     |                    | PJE0000001       | 1                 |       |
      | 001 | 5  | IINSURANCE   |                          |              | SGD | 1.0           | 1   | 30         | No            | GST0                   |                | 30.00                 | 30.00                |                       |                     |                    | PJE0000002       | 1                 |       |
      | 001 | 6  | IPENSIONS    |                          |              | SGD | 1.0           | 1   | 40         | No            | GST0                   |                | 40.00                 | 40.00                |                       |                     |                    | PJE0000002       | 1                 |       |
      | 001 | 7  | ITRANSALLO   |                          |              | SGD | 1.0           | 1   | 30         | Yes           | GST0                   |                | 30.00                 | 30.00                |                       |                     |                    | PJE0000002       | 1                 |       |
      | 001 | 8  | IENTERALLO   |                          |              | SGD | 1.0           | 1   | 55         | Yes           | GST0                   | GST10          | 50.00                 | 55.00                |                       |                     |                    | PJE0000002       | 1                 |       |
      | 001 | 9  | IOTHERALLO   |                          |              | SGD | 1.0           | 1   | 50         | No            | GST0                   | GST10          | 50.00                 | 55.00                |                       |                     |                    |                  |                   |       |
      | 001 | 10 | IGRATUITY    |                          |              | SGD | 1.0           | 1   | 60         | Yes           | GST0                   |                | 60.00                 | 60.00                |                       |                     |                    |                  |                   |       |
      | 001 | 11 | ICOMPENSA    |                          |              | SGD | 1.0           | 1   | 60         | Yes           | GST0                   |                | 60.00                 | 60.00                |                       |                     |                    |                  |                   |       |
      | 001 | 12 | IRETIRE92    |                          |              | SGD | 1.0           | 1   | 70         | Yes           | GST0                   |                | 70.00                 | 70.00                |                       |                     |                    |                  |                   |       |
      | 001 | 13 | IRETIRE93    |                          |              | SGD | 1.0           | 1   | 70         | Yes           | GST0                   |                | 70.00                 | 70.00                |                       |                     |                    |                  |                   |       |
      | 001 | 14 | IPENSIONO    |                          |              | SGD | 1.0           | 1   | 10         | Yes           | GST0                   |                | 10.00                 | 10.00                |                       |                     |                    |                  |                   |       |
      | 001 | 15 | IEXCESSCPF   |                          |              | SGD | 1.0           | 1   | 10         | Yes           | GST0                   |                | 10.00                 | 10.00                |                       |                     |                    |                  |                   |       |
      | 001 | 16 | ISTOCK       |                          |              | SGD | 1.0           | 1   | 10         | Yes           | GST0                   |                | 10.00                 | 10.00                |                       |                     |                    |                  |                   |       |
      | 001 | 17 | IBENEFIT     |                          |              | SGD | 1.0           | 1   | 10         | Yes           | GST0                   |                | 10.00                 | 10.00                |                       |                     |                    |                  |                   |       |
      | 002 | 1  | SALARYY      |                          |              | SGD | 1.0           | 5   | 10         | Yes           | GST0                   |                | 50.00                 | 50.00                |                       |                     |                    |                  |                   |       |
      | 003 | 1  | BONUSY       |                          |              | SGD | 1.0           | 2   | 50         | Yes           | GST0                   |                | 100.00                | 100.00               |                       |                     |                    |                  |                   |       |
      | 004 | 1  | ISALARY      |                          |              | SGD | 1.0           | 1   | 100        | Yes           | GST0                   |                | 100.00                | 100.00               |                       |                     |                    |                  |                   |       |
      | 004 | 2  | SALARYY      |                          |              | SGD | 1.0           | 2   | 100        | Yes           | GST0                   |                | 200.00                | 200.00               |                       |                     |                    | PJE0000001       | 3                 |       |
      | 004 | 3  | SALARYY      |                          |              | SGD | 1.0           | 3   | 100        | Yes           | GST0                   |                | 300.00                | 300.00               |                       |                     |                    | PJE0000001       | 4                 |       |
      | 004 | 4  | SALARYN      |                          |              | SGD | 1.0           | 4   | 100        | Yes           | GST0                   |                | 400.00                | 400.00               |                       |                     |                    | PJE0000001       | 1                 |       |
      | 004 | 5  | BONUSY       |                          |              | SGD | 1.0           | 2   | 500        | Yes           | GST0                   |                | 1,000.00              | 1,000.00             |                       |                     |                    | PJE0000001       | 5                 |       |
      | 005 | 1  | SALARYN      |                          |              | SGD | 1.0           | 2   | 100        | Yes           | GST0                   |                | 200.00                | 200.00               |                       |                     |                    | PJE0000001       | 2                 | 1     |
      | 006 | 1  | BONUSY       |                          |              | SGD | 1.0           | 2   | 250        | Yes           | GST0                   |                | 500.00                | 500.00               |                       |                     |                    | PJE0000001       | 2                 | 2     |
    Then user input Remarks in Draft state of Additional Payment by Recipient as as "<Remarks KEY>"
      | KEY | Internal Remark Code | Internal Remarks          | External Remark Code | External Remarks          |
      | 001 |                      | Internal Remarks for EMP1 |                      | External Remarks for EMP1 |
    Then user submits created voucher in Draft state of Additional Payment by Recipient
    Then user pulls out result in database into Excel file "After submit Additional Payment" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | File Name              | Sheet Name                | Replacement 1 Data Key | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select ADDITIONAL_PAYMENT_VCH_NO,DESCRIPTION,VOUCHER_TYPE,STATUS,WAGE_SERVICE_CODE,RECIPIENT_CODE,CURRENCY_CODE,SALES_TAX_CODE,SALES_TAX_VALUE,EXCHANGE_RATE,INCLUSIVE_TAX,IS_LAST_YEAR_BONUS,IS_ADHOC_PAYMENT,IS_MEDICAL_CLAIM,DEFAULT_UNIT_PRICE,DECLARE_APPROVAL_DATE,PAYOUT_DATE,SOURCE_VOUCHER_NO,CREATED_EMP,CREATED_DATE,LOAN_AMT,LOAN_AMT_DEDUCTED_PER_PAYRUN,CUMULATIVE_AMT_DEDUCTED,IS_INCLUDE_LOAN_IN_PAYSLIP,DEDUCT_LOAN_START_DATE,BANK_VOUCHER_NO,SERVICE_TYPE,POSTED_BY,POSTED_DATETIME,CREATED_BY,LAST_UPDATED_BY,REMARKS,EXTERNAL_REMARKS,APPROVAL_REMARKS,VOUCHER_DATE,PAYROLL_DATE,TOTAL_NATURE_BEF_TAX,TOTAL_NATURE_AFT_TAX,TOTAL_HOME_BEF_TAX,TOTAL_HOME_AFT_TAX from PY_ADDITIONAL_PAYMENT where ADDITIONAL_PAYMENT_VCH_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | AddPaymentByRecepient1 | PY_ADDITIONAL_PAYMENT     | Add Payment Voucher No |         |                        |         |
      | 001 | select SOURCE_VOUCHER_CODE,EMP_PAYROLL_CATEGORY_CODE,SEQ_NO,EPC_COUNT,CREATED_BY,LAST_UPDATED_BY from PY_ADDITIONAL_DEDUCTION_EPC where SOURCE_VOUCHER_CODE = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | AddPaymentByRecepient1 | PY_ADDITIONAL_DEDUCTION   | Add Payment Voucher No |         |                        |         |
      | 001 | select PY_COST_ALLOCATION_SEQ,SRC_TRANSACTION_CODE,SRC_VOUCHER_NO,SRC_VOUCHER_TYPE,SRC_LINE_SEQ,ALLOC_TYPE,ALLOC_COMPANY_CODE,ALLOC_VOUCHER_NO,ALLOC_PHASE_NO,ALLOC_LINE_NO,ALLOC_DATE,ALLOC_BY,COST_ALLOCATION_NO,CREATED_BY,LAST_UPDATED_BY,REMARKS from PY_COST_ALLOCATION where SRC_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | AddPaymentByRecepient1 | PY_COST_ALLOCATION        | Add Payment Voucher No |         |                        |         |
      | 001 | select B.COST_ALLOCATION_NO,B.LINE_ITEM_NO,B.DT_TYPE,B.TYPE,B.SERVICE_CODE,B.INVENTORY_CODE,B.GLAN_CODE,B.EMP_PAYROLL_CATEGORY_CODE,B.EMP_PAYROLL_CATEGORY_DESC,B.ADD_TOTAL_AMT,B.ADD_TOTAL_HOME_AMT,B.RED_TOTAL_AMT,B.RED_TOTAL_HOME_AMT,B.CREATED_BY,B.LAST_UPDATED_BY,B.LINE_ITEM_DESCRIPTION from PJ_COST_ALC_HST_DET AS B INNER JOIN PY_COST_ALLOCATION AS A ON A.COST_ALLOCATION_NO = B.COST_ALLOCATION_NO where A.SRC_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | AddPaymentByRecepient1 | PJ_COST_ALC_HST_DET       | Add Payment Voucher No |         |                        |         |
      | 001 | select C.COST_ALLOCATION_NO,C.LINE_ITEM_NO,C.ALLOCATION_NO,C.ALLOCATION_TYPE,C.SOURCE_VOUCHER_NO,C.SOURCE_PHASE_NO,C.SOURCE_LINE_ITEM_NO,C.SOURCE_SHIPMENT_NO,C.ALLOC_QTY,C.ALLOC_UNIT_COST,C.ADD_ALLOC_AMT,C.ADD_ALLOC_HOME_AMT,C.RED_ALLOC_AMT,C.RED_ALLOC_HOME_AMT,C.INSTALL_QTY,C.DISMANTLE_QTY,C.CREATED_BY,C.LAST_UPDATED_BY from PJ_COST_ALC_HST_DET_ALLOC AS C INNER JOIN (select B.COST_ALLOCATION_NO from PJ_COST_ALC_HST_DET AS B INNER JOIN PY_COST_ALLOCATION AS A ON A.COST_ALLOCATION_NO = B.COST_ALLOCATION_NO where A.SRC_VOUCHER_NO = '@@#1#@@') AS D ON D.COST_ALLOCATION_NO = C.COST_ALLOCATION_NO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | AddPaymentByRecepient1 | PJ_COST_ALC_HST_DET_ALLOC | Add Payment Voucher No |         |                        |         |
      | 001 | select C.COST_ALLOCATION_NO,C.COST_ALLOCATION_DATE,C.TYPE,C.YEAR_POSTED_TO,C.PERIOD_POSTED_TO,C.PROJECT_NO,C.CURRENCY_CODE,C.EXCH_RATE,C.REFERENCE_NO,C.REMARKS,C.INTERNAL_REMARKS,C.SOURCE_TYPE,C.SOURCE_VOUCHER_NO,C.SOURCE_COMPANY_CODE,C.EMP_PAYROLL_CATEGORY_CODE,C.VOUCHER_STATUS,C.CREATED_BY,C.LAST_UPDATED_BY from PJ_COST_ALC_HST_HDR AS C INNER JOIN (select B.COST_ALLOCATION_NO from PJ_COST_ALC_HST_DET AS B INNER JOIN PY_COST_ALLOCATION AS A ON A.COST_ALLOCATION_NO = B.COST_ALLOCATION_NO where A.SRC_VOUCHER_NO = '@@#1#@@') AS D ON D.COST_ALLOCATION_NO = C.COST_ALLOCATION_NO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | AddPaymentByRecepient1 | PJ_COST_ALC_HST_HDR       | Add Payment Voucher No |         |                        |         |
      | 001 | select C.MODULE_CODE,C.TRANSACTION_TYPE_CODE,C.SOURCE_VOUCHER_NO,C.GL_ENTRY_TYPE,C.LINE_ITEM_NO,C.IS_COMBINED,C.GL_ACC_CODE,C.VOUCHER_DATE,C.YEAR_POSTED_TO,C.PERIOD_POSTED_TO,C.CURRENCY_CODE,C.EXCH_RATE,C.NATURE_DEBIT,C.NATURE_CREDIT,C.HOME_DEBIT,C.HOME_CREDIT,C.TRANSACTION_ID,C.CREATED_BY,C.LAST_UPDATED_BY,C.MEMO,C.TRANSACTION_DESCRIPTION from GL_LEDGER_SUMMARY AS C INNER JOIN (select B.COST_ALLOCATION_NO from PJ_COST_ALC_HST_DET AS B INNER JOIN PY_COST_ALLOCATION AS A ON A.COST_ALLOCATION_NO = B.COST_ALLOCATION_NO where A.SRC_VOUCHER_NO = '@@#1#@@') AS D ON D.COST_ALLOCATION_NO = C.SOURCE_VOUCHER_NO                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | AddPaymentByRecepient1 | GL_LEDGER_SUMMARY         | Add Payment Voucher No |         |                        |         |
      | 001 | select EMPLOYEE_CODE,YEAR,COMPANY_CODE,ID_TYPE,ID_NOS,NAME_LINE1,NAME_LINE2,ADDRESS_TYPE,ADDRESS,BLOCK_HOUSE_NO,STREET_NAME,LEVEL_NO,UNIT_NO,POSTAL_CODE,ADDRESS_LINE1,ADDRESS_LINE2,ADDRESS_LINE3,POSTAL_CODE_UNFORMATTED_ADDR,COUNTRY_CODE,TH_COUNTRY_CODE,NATIONALITY_CODE,BANK_NAME,RET_BENIFIT_FUND,SEX,DOB,AMOUNT,FROM_DATE,TO_DATE,MOSQUE_BUILDING_FUND_AMT,DONATION_AMT,CPF_FUND_AMT,INSURANCE_AMT,ADDITIONAL_SALARY_AMT,BONUS_AMT,DIRECTOR_FEE_AMT,OTHERS_AMT,GAINS_PROFIT_SHARE_OP_AMT,EXEMPT_REMISSION_AMT,BENEFITS_IN_KIND,BENEFITS_IN_KIND_AMT,GRATUITY_IN_LIEU_NOTICE,COMP_RETRENCHMENT_BENEFIT,APPROVAL_OBTAINED_IRAS,DATE_OF_APPROVAL,CESSATION_PROVISIONS,FORM_IR8S,EXEMPT_REMISSION_INCOME_TYPE,GROSS_COMMISSION_AMT,GROSS_FROM_DATE,GROSS_TO_DATE,GROSS_COMMISSION_INDICATOR,PENSION_AMT,TRANSPORT_ALLOWANCE_AMT,ENTERTAINMENT_ALLOWANCE_AMT,OTHERS_ALLOWANCES_AMT,GRATUITY_AMT,COMPENSATION_BENEFITS_AMT,RETIREMENT_BENEFIT_92_AMT,RETIREMENT_BENEFIT_93_AMT,CONTRI_PENSION_OUT_SG_AMT,EXCESS_CONTRI_CPF_AMT,GAINS_PROFIT_FOR_S10_AMT,VALUE_BENEFITS_IN_KINDS_AMT,AW_SUBJECT_TO_CPF_AMT,AW_TO_EMPLOYEE_CPF_AMT,OW_TO_EMPLOYEE_CPF_AMT,AW_TO_EMPLOYER_CPF_AMT,OW_TO_EMPLOYER_CPF_AMT,COMMENCEMENT_DATE,CESSATION_DATE,BONUS_DECLARATION_DATE,DIRECTOR_FEE_APPROVAL_DATE,OW_EMPLOYEE_AMT,AW_EMPLOYEE_AMT,AW_EMPLOYER_AMT,BASIC_SALARY,OVER_CONTRIBUTION_AW_AMT,OVER_EMPLOYEE_AW_AMT,OVER_EMPLOYER_AW_AMT,OVER_AW_SUBJECT_CPF,EMPLOYER_CPF_CONTRIBUTIONS,EMPLOYEE_CPF_CONTRIBUTIONS,CREATED_BY,LAST_UPDATED_BY,SALARY_AMT_TEMP,SALARY_AMT from PY_IR8A where EMPLOYEE_CODE = 'EMP1' | AddPaymentByRecepient1 | PY_IR8A                   | Add Payment Voucher No |         |                        |         |

    Examples: 
      | Login User KEY | Module Config KEY | Additional Payment KEY | Recipient KEY | Wage Services KEY | Remarks KEY | Pullout Excel KEY | DATABASE KEY |
      | 001            | 001               | 001                    | 001           | 001               | 001         | 001               | 001          |
      | 001            |                   | 001                    | 001           | 002               | 001         | 001               | 001          |
      | 001            |                   | 001                    | 001           | 003               | 001         | 001               | 001          |
      | 001            |                   | 001                    | 001           | 004               | 001         | 001               | 001          |
      | 001            | 002               | 001                    | 001           | 005               | 001         | 001               | 001          |
      | 001            |                   | 001                    | 001           | 006               | 001         | 001               | 001          |

  Scenario Outline: Generates payslip and submit
    Given user logins to Task Hub as "<Login User KEY>"
      | KEY | User Name | Password | Company |
      | 001 | vincent1  | taskhub  | (TRG6)  |
    Given user changes database connection as "<DATABASE KEY>"
      | KEY | JDBC_DRIVER               | IP_SERVER   | SERVER_PORT | DB_NAME  | USER_NAME | PASS_WORD |
      | 001 | com.ibm.db2.jcc.DB2Driver | 172.18.0.10 | 50000       | GENMAIN6 | db2admin  | Taskhub1  |
    When user generates payslip for Additional Payment as "<Generation KEY>"
      | KEY | Payroll GL Posting Date | Year | Month | Payment Cycle Code | Payment Cycle No | Generate Payslip for advancement | Generate Payslip By       | EPC   | Submit |
      | 001 | 05/08/2016              | 2016 | 8     | AMONTHLY           | 1st              | N                                | Employee Payroll Category | DPEPC | Y      |
    Then user pulls out result in database into Excel file "after generate payslip" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | File Name              | Sheet Name                     | Replacement 1 Data Key  | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select MODULE_CODE,TRANSACTION_TYPE_CODE,SOURCE_VOUCHER_NO,GL_ENTRY_TYPE,LINE_ITEM_NO,IS_COMBINED,GL_ACC_CODE,VOUCHER_DATE,YEAR_POSTED_TO,PERIOD_POSTED_TO,CURRENCY_CODE,EXCH_RATE,NATURE_DEBIT,NATURE_CREDIT,HOME_DEBIT,HOME_CREDIT,TRANSACTION_ID,CREATED_BY,LAST_UPDATED_BY,MEMO,TRANSACTION_DESCRIPTION from GL_LEDGER_SUMMARY where SOURCE_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | AddPaymentByRecepient1 | GL_LEDGER_SUMMARY              | PY_GENERATION_VOUCHERNO |         |                        |         |
      | 001 | select EMPLOYEE_CODE,YEAR,COMPANY_CODE,ID_TYPE,ID_NOS,NAME_LINE1,NAME_LINE2,ADDRESS_TYPE,ADDRESS,BLOCK_HOUSE_NO,STREET_NAME,LEVEL_NO,UNIT_NO,POSTAL_CODE,ADDRESS_LINE1,ADDRESS_LINE2,ADDRESS_LINE3,POSTAL_CODE_UNFORMATTED_ADDR,COUNTRY_CODE,TH_COUNTRY_CODE,NATIONALITY_CODE,BANK_NAME,RET_BENIFIT_FUND,SEX,DOB,AMOUNT,FROM_DATE,TO_DATE,MOSQUE_BUILDING_FUND_AMT,DONATION_AMT,CPF_FUND_AMT,INSURANCE_AMT,ADDITIONAL_SALARY_AMT,BONUS_AMT,DIRECTOR_FEE_AMT,OTHERS_AMT,GAINS_PROFIT_SHARE_OP_AMT,EXEMPT_REMISSION_AMT,BENEFITS_IN_KIND,BENEFITS_IN_KIND_AMT,GRATUITY_IN_LIEU_NOTICE,COMP_RETRENCHMENT_BENEFIT,APPROVAL_OBTAINED_IRAS,DATE_OF_APPROVAL,CESSATION_PROVISIONS,FORM_IR8S,EXEMPT_REMISSION_INCOME_TYPE,GROSS_COMMISSION_AMT,GROSS_FROM_DATE,GROSS_TO_DATE,GROSS_COMMISSION_INDICATOR,PENSION_AMT,TRANSPORT_ALLOWANCE_AMT,ENTERTAINMENT_ALLOWANCE_AMT,OTHERS_ALLOWANCES_AMT,GRATUITY_AMT,COMPENSATION_BENEFITS_AMT,RETIREMENT_BENEFIT_92_AMT,RETIREMENT_BENEFIT_93_AMT,CONTRI_PENSION_OUT_SG_AMT,EXCESS_CONTRI_CPF_AMT,GAINS_PROFIT_FOR_S10_AMT,VALUE_BENEFITS_IN_KINDS_AMT,AW_SUBJECT_TO_CPF_AMT,AW_TO_EMPLOYEE_CPF_AMT,OW_TO_EMPLOYEE_CPF_AMT,AW_TO_EMPLOYER_CPF_AMT,OW_TO_EMPLOYER_CPF_AMT,COMMENCEMENT_DATE,CESSATION_DATE,BONUS_DECLARATION_DATE,DIRECTOR_FEE_APPROVAL_DATE,OW_EMPLOYEE_AMT,AW_EMPLOYEE_AMT,AW_EMPLOYER_AMT,BASIC_SALARY,OVER_CONTRIBUTION_AW_AMT,OVER_EMPLOYEE_AW_AMT,OVER_EMPLOYER_AW_AMT,OVER_AW_SUBJECT_CPF,EMPLOYER_CPF_CONTRIBUTIONS,EMPLOYEE_CPF_CONTRIBUTIONS,CREATED_BY,LAST_UPDATED_BY,SALARY_AMT_TEMP,SALARY_AMT from PY_IR8A where EMPLOYEE_CODE = 'EMP1'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | AddPaymentByRecepient1 | PY_IR8A                        |                         |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO,PAYSLIP_VOUCHER_NO,EMPLOYEE_CODE,COMPANY_CODE,HOURLY_RATE_GROUP_CODE,EMP_PAYROLL_CATEGORY_CODE,PAYSLIP_TYPE,SALARY_TYPE,PAYMENT_CYCLE_NO,PAYMENT_METHOD,PAYMENT_FREQUENCY,IS_SALARY_ON_HOLD,IS_ZERO_PAYSLIP,BASIC_SALARY,SEGMENT_1_CODE,SEGMENT_2_CODE,SEGMENT_3_CODE,SEGMENT_4_CODE,CHEQUE_NO,EMPLOYER_BANK_CODE,EMPLOYEE_BANK_CODE,EMPLOYER_BANK_ACC_NO,EMPLOYEE_BANK_ACC_NO,IS_GENERATED_GLAN,TOTAL_FIXED_ADD_PYMT_AMT,TOTAL_LEAVE_ENCASHMENT_AMT,TOTAL_FIXED_ADD_BEFORE_TAX_AMT,TOTAL_FIXED_ADD_TAX_AMT,TOTAL_ADD_PYMT_AMT,TOTAL_ADD_PYMT_BEFORE_TAX_AMT,TOTAL_ADD_PYMT_TAX_AMT,TOTAL_FIXED_DED_BEFORE_TAX_AMT,TOTAL_FIXED_DED_TAX_AMT,TOTAL_DAILY_ALLOWANCE_AMT,TOTAL_PIECE_RATE_AMT,TOTAL_TIMESHEET_AMT,TOTAL_NOT_INCL_TIMESHEET_AMT,ORDINARY_WAGE_SUBJ_CPF,EMPLOYER_CPF_CONTRIBUTIONS,EMPLOYEE_CPF_CONTRIBUTIONS,TOTAL_SAL_ON_HOLD_RELEASED,TOTAL_SALARY_AMT_PAID,TAX_ON_HOLD_PER_PAYRUN,TAX_ON_HOLD_RELEASED_AMT,LOAN_AMT_PER_PAYRUN,TOTAL_LOAN_DEDUCTED_AMT,OLD_LOAN_DEDUCTED_PER_PAYRUN,OLD_LOAN_AMT,OLD_CUMULATIVE_DEDUCTED_AMT,TOTAL_FIXED_DEDUCTION_AMT,TOTAL_PAYROLL_DEDUCTION_AMT,TOTAL_DEDUCTION_BEFORE_AMT,TOTAL_DEDUCTION_TAX_AMT,TOTAL_LEAVE_PENALTY_AMT,TOTAL_COMM_FUND_DONATION,DEDUCT_SALARY_LEAVE_AMT,TOTAL_NEGATIVE_SALARY,SKILL_DEVELOPMENT_LEVY,ADDITIONAL_WAGE_SUBJ_CPF,ACTUAL_AW_AMT,STATUS,STOCK_ISSUE_DEDUCTION_AMT,TOTAL_PIECE_RATE_ON_HOLD_AMT,WORKSHEET_ON_HOLD,WORKSHEET_HOLD_RELEASE_AMT,WORKING_GROUP_CODE,DESIGNATION_GROUP_CODE,PAYROLL_REPORT_GROUP_CODE,PIECE_RATE_GROUP_CODE,WORKING_LOCATION_CODE,EMPLOYER_CPF_SUBMISSION_NO,REAL_WORKING_DAYS,PAYRUN_REAL_WORKING_DAYS,OLD_TAX_ON_HOLD_CUMULATIVE_AMT,AW_TO_EMPLOYEE_CPF_AMT,OW_TO_EMPLOYEE_CPF_AMT,AW_TO_EMPLOYER_CPF_AMT,OW_TO_EMPLOYER_CPF_AMT,CPF_TYPE,PJ_ALLOC_STATUS,OVER_CONTRIBUTION_AW_AMT,OVER_EMPLOYEE_AW_AMT,OVER_AW_SUBJECT_CPF,TOTAL_WORKING_HOURS_PER_WEEK,TOTAL_WORKING_HOURS_PER_DAY,TOTAL_ADVANCEMENT_AMT,CREATED_EMP,POSTED_BY,CREATED_BY,LAST_UPDATED_BY,IS_BASIC_SAL_UP_LEAVE_ALLOC,TOTAL_EXCESS_OT_AMT,PREV_EMPLOYEE_CPF,PREV_EMPLOYER_CPF,PREV_AW_SUBJECTED_CPF,PREV_OW_SUBJECTED_CPF,DATE_OF_PAYMENT,PAYSLIP_VOUCHER_DATE,PAYSLIP_START_DATE,PAYSLIP_END_DATE,POSTED_DATETIME,TOTAL_LEAVE_PAYBACK_AMT,TOTAL_PH_AMT,TOTAL_FWL_AMT from PY_PAYSLIP where PY_GENERATION_VOUCHER_NO = '@@#1#@@' | AddPaymentByRecepient1 | PY_PAYSLIP                     | PY_GENERATION_VOUCHERNO |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO,PAYSLIP_VOUCHER_NO,ADDITIONAL_PAYMENT_VCH_NO,SEQ_NO,PROJECT_NO,ADD_PYMT_AMT,SERVICE_CODE,CREATED_BY,LAST_UPDATED_BY from PY_PAYSLIP_ADDITIONAL_PYMT where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | AddPaymentByRecepient1 | PY_PAYSLIP_ADDITIONAL_PYMT     | PY_GENERATION_VOUCHERNO |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO,PAYSLIP_VOUCHER_NO,DAILY_ALLOWANCE_SUBJ_CPF_ADD,FIXED_ADDITIONAL_SUBJ_CPF_ADD,ADDITIONAL_SUBJ_CPF_ADD,FIXED_DEDUCTION_SUBJ_CPF_ADD,DEDUCTION_SUBJ_CPF_ADD,CREATED_BY,LAST_UPDATED_BY from PY_PAYSLIP_ADDITIONAL_WAGE_CPF where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | AddPaymentByRecepient1 | PY_PAYSLIP_ADDITIONAL_WAGE_CPF | PY_GENERATION_VOUCHERNO |         |                        |         |
    And user submits payslip for Additional Payment as "<Payslip KEY>"
      | KEY | Voucher No               |
      | 001 | @CreatedGenerateVoucher@ |
    Then user pulls out result in database into Excel file "after submit payslip" as "<Pullout Excel KEY>"
      | KEY | SQL Statement                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | File Name              | Sheet Name                     | Replacement 1 Data Key  | Index 1 | Replacement 2 Data Key | Index 2 |
      | 001 | select MODULE_CODE,TRANSACTION_TYPE_CODE,SOURCE_VOUCHER_NO,GL_ENTRY_TYPE,LINE_ITEM_NO,IS_COMBINED,GL_ACC_CODE,VOUCHER_DATE,YEAR_POSTED_TO,PERIOD_POSTED_TO,CURRENCY_CODE,EXCH_RATE,NATURE_DEBIT,NATURE_CREDIT,HOME_DEBIT,HOME_CREDIT,TRANSACTION_ID,CREATED_BY,LAST_UPDATED_BY,MEMO,TRANSACTION_DESCRIPTION from GL_LEDGER_SUMMARY where SOURCE_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | AddPaymentByRecepient1 | GL_LEDGER_SUMMARY              | PY_GENERATION_VOUCHERNO |         |                        |         |
      | 001 | select EMPLOYEE_CODE,YEAR,COMPANY_CODE,ID_TYPE,ID_NOS,NAME_LINE1,NAME_LINE2,ADDRESS_TYPE,ADDRESS,BLOCK_HOUSE_NO,STREET_NAME,LEVEL_NO,UNIT_NO,POSTAL_CODE,ADDRESS_LINE1,ADDRESS_LINE2,ADDRESS_LINE3,POSTAL_CODE_UNFORMATTED_ADDR,COUNTRY_CODE,TH_COUNTRY_CODE,NATIONALITY_CODE,BANK_NAME,RET_BENIFIT_FUND,SEX,DOB,AMOUNT,FROM_DATE,TO_DATE,MOSQUE_BUILDING_FUND_AMT,DONATION_AMT,CPF_FUND_AMT,INSURANCE_AMT,ADDITIONAL_SALARY_AMT,BONUS_AMT,DIRECTOR_FEE_AMT,OTHERS_AMT,GAINS_PROFIT_SHARE_OP_AMT,EXEMPT_REMISSION_AMT,BENEFITS_IN_KIND,BENEFITS_IN_KIND_AMT,GRATUITY_IN_LIEU_NOTICE,COMP_RETRENCHMENT_BENEFIT,APPROVAL_OBTAINED_IRAS,DATE_OF_APPROVAL,CESSATION_PROVISIONS,FORM_IR8S,EXEMPT_REMISSION_INCOME_TYPE,GROSS_COMMISSION_AMT,GROSS_FROM_DATE,GROSS_TO_DATE,GROSS_COMMISSION_INDICATOR,PENSION_AMT,TRANSPORT_ALLOWANCE_AMT,ENTERTAINMENT_ALLOWANCE_AMT,OTHERS_ALLOWANCES_AMT,GRATUITY_AMT,COMPENSATION_BENEFITS_AMT,RETIREMENT_BENEFIT_92_AMT,RETIREMENT_BENEFIT_93_AMT,CONTRI_PENSION_OUT_SG_AMT,EXCESS_CONTRI_CPF_AMT,GAINS_PROFIT_FOR_S10_AMT,VALUE_BENEFITS_IN_KINDS_AMT,AW_SUBJECT_TO_CPF_AMT,AW_TO_EMPLOYEE_CPF_AMT,OW_TO_EMPLOYEE_CPF_AMT,AW_TO_EMPLOYER_CPF_AMT,OW_TO_EMPLOYER_CPF_AMT,COMMENCEMENT_DATE,CESSATION_DATE,BONUS_DECLARATION_DATE,DIRECTOR_FEE_APPROVAL_DATE,OW_EMPLOYEE_AMT,AW_EMPLOYEE_AMT,AW_EMPLOYER_AMT,BASIC_SALARY,OVER_CONTRIBUTION_AW_AMT,OVER_EMPLOYEE_AW_AMT,OVER_EMPLOYER_AW_AMT,OVER_AW_SUBJECT_CPF,EMPLOYER_CPF_CONTRIBUTIONS,EMPLOYEE_CPF_CONTRIBUTIONS,CREATED_BY,LAST_UPDATED_BY,SALARY_AMT_TEMP,SALARY_AMT from PY_IR8A where EMPLOYEE_CODE = 'EMP1'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | AddPaymentByRecepient1 | PY_IR8A                        |                         |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO,PAYSLIP_VOUCHER_NO,EMPLOYEE_CODE,COMPANY_CODE,HOURLY_RATE_GROUP_CODE,EMP_PAYROLL_CATEGORY_CODE,PAYSLIP_TYPE,SALARY_TYPE,PAYMENT_CYCLE_NO,PAYMENT_METHOD,PAYMENT_FREQUENCY,IS_SALARY_ON_HOLD,IS_ZERO_PAYSLIP,BASIC_SALARY,SEGMENT_1_CODE,SEGMENT_2_CODE,SEGMENT_3_CODE,SEGMENT_4_CODE,CHEQUE_NO,EMPLOYER_BANK_CODE,EMPLOYEE_BANK_CODE,EMPLOYER_BANK_ACC_NO,EMPLOYEE_BANK_ACC_NO,IS_GENERATED_GLAN,TOTAL_FIXED_ADD_PYMT_AMT,TOTAL_LEAVE_ENCASHMENT_AMT,TOTAL_FIXED_ADD_BEFORE_TAX_AMT,TOTAL_FIXED_ADD_TAX_AMT,TOTAL_ADD_PYMT_AMT,TOTAL_ADD_PYMT_BEFORE_TAX_AMT,TOTAL_ADD_PYMT_TAX_AMT,TOTAL_FIXED_DED_BEFORE_TAX_AMT,TOTAL_FIXED_DED_TAX_AMT,TOTAL_DAILY_ALLOWANCE_AMT,TOTAL_PIECE_RATE_AMT,TOTAL_TIMESHEET_AMT,TOTAL_NOT_INCL_TIMESHEET_AMT,ORDINARY_WAGE_SUBJ_CPF,EMPLOYER_CPF_CONTRIBUTIONS,EMPLOYEE_CPF_CONTRIBUTIONS,TOTAL_SAL_ON_HOLD_RELEASED,TOTAL_SALARY_AMT_PAID,TAX_ON_HOLD_PER_PAYRUN,TAX_ON_HOLD_RELEASED_AMT,LOAN_AMT_PER_PAYRUN,TOTAL_LOAN_DEDUCTED_AMT,OLD_LOAN_DEDUCTED_PER_PAYRUN,OLD_LOAN_AMT,OLD_CUMULATIVE_DEDUCTED_AMT,TOTAL_FIXED_DEDUCTION_AMT,TOTAL_PAYROLL_DEDUCTION_AMT,TOTAL_DEDUCTION_BEFORE_AMT,TOTAL_DEDUCTION_TAX_AMT,TOTAL_LEAVE_PENALTY_AMT,TOTAL_COMM_FUND_DONATION,DEDUCT_SALARY_LEAVE_AMT,TOTAL_NEGATIVE_SALARY,SKILL_DEVELOPMENT_LEVY,ADDITIONAL_WAGE_SUBJ_CPF,ACTUAL_AW_AMT,STATUS,STOCK_ISSUE_DEDUCTION_AMT,TOTAL_PIECE_RATE_ON_HOLD_AMT,WORKSHEET_ON_HOLD,WORKSHEET_HOLD_RELEASE_AMT,WORKING_GROUP_CODE,DESIGNATION_GROUP_CODE,PAYROLL_REPORT_GROUP_CODE,PIECE_RATE_GROUP_CODE,WORKING_LOCATION_CODE,EMPLOYER_CPF_SUBMISSION_NO,REAL_WORKING_DAYS,PAYRUN_REAL_WORKING_DAYS,OLD_TAX_ON_HOLD_CUMULATIVE_AMT,AW_TO_EMPLOYEE_CPF_AMT,OW_TO_EMPLOYEE_CPF_AMT,AW_TO_EMPLOYER_CPF_AMT,OW_TO_EMPLOYER_CPF_AMT,CPF_TYPE,PJ_ALLOC_STATUS,OVER_CONTRIBUTION_AW_AMT,OVER_EMPLOYEE_AW_AMT,OVER_AW_SUBJECT_CPF,TOTAL_WORKING_HOURS_PER_WEEK,TOTAL_WORKING_HOURS_PER_DAY,TOTAL_ADVANCEMENT_AMT,CREATED_EMP,POSTED_BY,CREATED_BY,LAST_UPDATED_BY,IS_BASIC_SAL_UP_LEAVE_ALLOC,TOTAL_EXCESS_OT_AMT,PREV_EMPLOYEE_CPF,PREV_EMPLOYER_CPF,PREV_AW_SUBJECTED_CPF,PREV_OW_SUBJECTED_CPF,DATE_OF_PAYMENT,PAYSLIP_VOUCHER_DATE,PAYSLIP_START_DATE,PAYSLIP_END_DATE,POSTED_DATETIME,TOTAL_LEAVE_PAYBACK_AMT,TOTAL_PH_AMT,TOTAL_FWL_AMT from PY_PAYSLIP where PY_GENERATION_VOUCHER_NO = '@@#1#@@' | AddPaymentByRecepient1 | PY_PAYSLIP                     | PY_GENERATION_VOUCHERNO |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO,PAYSLIP_VOUCHER_NO,ADDITIONAL_PAYMENT_VCH_NO,SEQ_NO,PROJECT_NO,ADD_PYMT_AMT,SERVICE_CODE,CREATED_BY,LAST_UPDATED_BY from PY_PAYSLIP_ADDITIONAL_PYMT where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | AddPaymentByRecepient1 | PY_PAYSLIP_ADDITIONAL_PYMT     | PY_GENERATION_VOUCHERNO |         |                        |         |
      | 001 | select PY_GENERATION_VOUCHER_NO,PAYSLIP_VOUCHER_NO,DAILY_ALLOWANCE_SUBJ_CPF_ADD,FIXED_ADDITIONAL_SUBJ_CPF_ADD,ADDITIONAL_SUBJ_CPF_ADD,FIXED_DEDUCTION_SUBJ_CPF_ADD,DEDUCTION_SUBJ_CPF_ADD,CREATED_BY,LAST_UPDATED_BY from PY_PAYSLIP_ADDITIONAL_WAGE_CPF where PY_GENERATION_VOUCHER_NO = '@@#1#@@'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | AddPaymentByRecepient1 | PY_PAYSLIP_ADDITIONAL_WAGE_CPF | PY_GENERATION_VOUCHERNO |         |                        |         |
    Then user compares pulled out Excel file with Reference Excel file as "<Compare KEY>"
      | KEY | Output File Name       | Reference File Name    | Checksum Difference |
      | 001 | AddPaymentByRecepient1 | AddPaymentByRecepient1 | 1252                |

    Examples: 
      | Login User KEY | DATABASE KEY | Pullout Excel KEY | Generation KEY | Payslip KEY | Compare KEY |
      | 001            | 001          | 001               | 001            | 001         | 001         |
